version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: update yum
          command: sudo yum update
      - run:
          name: install docker dependecies
          command: sudo yum install -y yum-utils device-mapper-persistent-data lvm2
      - run:
          name: install docker repository
          command: sudo yum-config-manager --dd-repo https://download.docker.com/linux/centos/docker-ce.repo
      - run:
          name: update registry
          command: sudo yum update
      - run:
          name: install docker-ce
          command: sudo install -y docker-ce
          
